
spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos服务地址
  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community-user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: WX030330.

  #Redis
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
    password:
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0
    database: 3
    # 连接超时时间（毫秒）
    timeout: 1000
    #Redis连接池
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 10