
spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos服务地址
  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community-friend?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
  #Redis
  data:
    redis:
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接密码（默认为空）
      password:
      # Redis服务器连接端口
      port: 6379
      # Redis数据库索引（默认为0
      database: 3
      # 连接超时时间（毫秒）
      timeout: 1000
      #Redis连接池
      jedis:
        pool:
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 200
          # 连接池中的最大空闲连接
          max-idle: 10
  #RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

#MyBatis-plus
mybatis-plus:
  # 指定Mapper XML文件的位置，使用classpath通配符指定路径。
  mapper-locations: classpath*:com/yanty/friends/mapper/xml/*Mapper.xml
  # 指定实体类的包路径，用于自动扫描并注册类型别名。
  type-aliases-package: com.yanty.friends.entity.*
  # 全局配置
  global-config:
    db-config:
      #驼峰下划线转换（将数据库字段的下划线命名规则转换为 Java 实体类属性的驼峰命名规则）
      table-underline: true
      #表名前缀
      table-prefix:
  configuration:
    # 将 Java 实体类属性的驼峰命名规则转换为数据库字段的下划线命名规则
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 是否开启二级缓存。
    cache-enabled: false

#feign远程调用
feign:
  client:
    config:
      default:
        loggerLevel: BASIC #日志级别
  #feign连接池
  httpclient:
    enabled: true #开启feign对HttpClient的支持
    max-connections: 200  #最大的连接数
    max-connections-per-route: 50 #每个路径的最大连接数