server:
  port: 8080
spring:
  application:
    name: community-user
  cloud:
    nacos:
      server-addr: localhost:8848

#feign远程调用
feign:
  client:
    config:
      default:
        loggerLevel: BASIC #日志级别
  #feign连接池
  httpclient:
    enabled: true #开启feign对HttpClient的支持
    max-connections: 200  #最大的连接数
    max-connections-per-route: 50 #每个路径的最大连接数