server:
  port: 8080
spring:
  #nacos服务注册
  application:
    name: UserService #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #服务地址

  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community-user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: WX030330.

  #Redis
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
    password:
    # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0
    database: 3
    # 连接超时时间（毫秒）
    timeout: 1000
    #Redis连接池
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 10

#MyBatis-plus
mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: true
  mapper-locations: classpath*:org/gulanthys/user/mapper/xml/*Mapper.xml
  type-aliases-package: org.gulanthys.user.entity

#feign远程调用
feign:
  client:
    config:
      default:
        loggerLevel: BASIC #日志级别
  #feign连接池
  httpclient:
    enabled: true #开启feign对HttpClient的支持
    max-connections: 200  #最大的连接数
    max-connections-per-route: 50 #每个路径的最大连接数

